dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
install:
  - pip install -r dev-requirements.txt
  - pip install flake8
  - pip install coveralls
before_script: flake8
script: pytest
after_success: coveralls
