---
apiVersion: v1
kind: Namespace
metadata:
  name: kubemen

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemen
  labels:
    app: kubemen
  namespace: kubemen
rules:
- apiGroups: ["*"]
  resources: [
  "cronjobs",
  "daemonsets",
  "deployments",
  "events",
  "horizontalpodautoscalers",
  "ingresses",
  "jobs",
  "pods",
  "replicasets",
  "replicationcontrollers",
  "services",
  "statefulsets",
  "certificates",
  "configmaps",
  "endpoints",
  "limitranges",
  "networkpolicies",
  "persistentvolumeclaims",
  "resourcequotas",
  "rolebindings",
  "roles",
  "secrets",
  "serviceaccounts"
  ]
  verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemen
  labels:
    app: kubemen
  namespace: kubemen

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubemen
  labels:
    app: kubemen
  namespace: kubemen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubemen
subjects:
  - kind: ServiceAccount
    name: kubemen
    namespace: kubemen
